endpoints.metrics.enabled: true
management.security.enabled: false
liquibase.change-log: classpath:db.migration/db_init.yml
badrequest.error.message: Sorry, Nothing here
spring.h2.console.enabled: true
spring:
  jackson:
    serialization:
       WRITE_DATES_AS_TIMESTAMPS: false
  datasource:
    type: com.zaxxer.hikari.HikariDataSource

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

